# fly.toml app configuration file generated for stock-monitor-solitary-lake-5718 on 2025-01-22T11:14:46+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-monitor-solitary-lake-5718'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python -m app.monitoring.real_time_monitor'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
