services:
  - type: worker
    name: stock-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.real_time_monitor
    autoDeploy: true

    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_IDS
        sync: false
      - key: PORT
        value: 8080 